class Fighter:
    def __init__(self, name, division, power, speed, grappling, popularity):
        self.name = name
        self.division = division
        self.power = power
        self.speed = speed
        self.grappling = grappling
        self.popularity = popularity




fighter_database = {
    "Tom Aspinall": Fighter("Tom Aspinall", "Heavyweight", 92, 87, 88, 90),
    "Ciryl Gane": Fighter("Ciryl Gane", "Heavyweight", 87, 90, 80, 78),
    "Alexander Volkov": Fighter("Alexander Volkov", "Heavyweight", 88, 78, 75, 60),
    "Sergei Pavlovich": Fighter("Sergey Pavlovich", "Heavyweight", 94, 75, 65, 55), 
    "Curtis Blaydes": Fighter("Curtis Blaydes", "Heavyweight", 85, 70, 92, 50),
    "Jailton Almeida": Fighter("Jailton Almeida", "Heavyweight", 82, 75, 90, 58),
    "Waldo Cortes-Acosta": Fighter("Waldo Cortes-Acosta", "Heavyweight", 84, 70, 60, 35),
    "Marcin Tybura": Fighter("Marcin Tybura", "Heavyweight", 80, 68, 80, 45),
    "Serghei Spivac": Fighter("Serghei Spivac", "Heavyweight", 85, 68, 88, 48),
    "Derrick Lewis": Fighter("Derrick Lewis", "Heavyweight", 96, 60, 55, 80),
    "Tai Tuivasa": Fighter("Tai Tuivasa", "Heavyweight", 89, 65, 60, 70),
    "Shamil Gaziev": Fighter("Shamil Gaziev", "Heavyweight", 88, 65, 70, 35),
    "Mick Parkin": Fighter("Mick Parkin", "Heavyweight", 80, 65, 75, 28),
    "Tallison Teixeira": Fighter("Tallison Teixeira", "Heavyweight", 78, 62, 70, 22),
    "Jhonata Diniz": Fighter("Jhonata Diniz", "Heavyweight", 87, 70, 60, 30),
    "Martin Buday": Fighter("Martin Buday", "Heavyweight", 79, 62, 72, 33),
    "Kennedy Nzechukwu": Fighter("Kennedy Nzechukwu", "Heavyweight", 83, 72, 65, 40),
    "Mario Pinto": Fighter("Mario Pinto", "Heavyweight", 76, 60, 68, 20),
    "Hamdy Abdelwahab": Fighter("Hamdy Abdelwahab", "Heavyweight", 80, 60, 85, 25),
    "Thomas Petersen": Fighter("Thomas Petersen", "Heavyweight", 79, 63, 72, 24),
    "Valter Walker": Fighter("Valter Walker", "Heavyweight", 77, 65, 70, 26),
    "Ryan Spann": Fighter("Ryan Spann", "Heavyweight", 86, 75, 80, 45),
    "Junior Tafa": Fighter("Junior Tafa", "Heavyweight", 85, 68, 55, 30),
    "Chris Barnett": Fighter("Chris Barnett", "Heavyweight", 88, 60, 60, 38),
    "Sean Sharaf": Fighter("Sean Sharaf", "Heavyweight", 75, 58, 65, 18),
    "Austen Lane": Fighter("Austen Lane", "Heavyweight", 80, 68, 65, 28),
    "Mohammed Usman": Fighter("Mohammed Usman", "Heavyweight", 80, 68, 70, 35),
    "Justin Tafa": Fighter("Justin Tafa", "Heavyweight", 90, 60, 50, 32),
    "Lukasz Brzeski": Fighter("Lukasz Brzeski", "Heavyweight", 75, 60, 70, 20),

    "Magomed Ankalaev": Fighter("Magomed Ankalaev", "Light Heavyweight", 90, 85, 85, 82),
    "Alex Pereira": Fighter("Alex Pereira", "Light Heavyweight", 95, 87, 80, 98),
    "Jiri Prochazka": Fighter("Jiri Prochazka", "Light Heavyweight", 92, 85, 78, 90),
    "Carlos Ulberg": Fighter("Carlos Ulberg", "Light Heavyweight", 87, 80, 60, 40),
    "Jamahal Hill": Fighter("Jamahal Hill", "Light Heavyweight", 88, 82, 75, 80),
    "Jan Blachowicz": Fighter("Jan Blachowicz", "Light Heavyweight", 89, 78, 80, 75),
    "Aleksandar Rakic": Fighter("Aleksandar Rakic", "Light Heavyweight", 89, 80, 78, 70),
    "Khalil Rountree Jr.": Fighter("Khalil Rountree Jr.", "Light Heavyweight", 88, 80, 68, 62),
    "Dominick Reyes": Fighter("Dominick Reyes", "Light Heavyweight", 86, 78, 70, 65),
    "Volkan Oezdemir": Fighter("Volkan Oezdemir", "Light Heavyweight", 85, 75, 70, 58),
    "Nikita Krylov": Fighter("Nikita Krylov", "Light Heavyweight", 82, 80, 75, 55),
    "Azamat Murzakanov": Fighter("Azamat Murzakanov", "Light Heavyweight", 85, 75, 80, 40),
    "Johnny Walker": Fighter("Johnny Walker", "Light Heavyweight", 87, 85, 70, 65),
    "Bogdan Guskov": Fighter("Bogdan Guskov", "Light Heavyweight", 83, 75, 60, 30),
    "Zhang Mingyang": Fighter("Zhang Mingyang", "Light Heavyweight", 85, 70, 65, 30),
    "Alonzo Menifield": Fighter("Alonzo Menifield", "Light Heavyweight", 84, 72, 68, 38),
    "Navajo Stirling": Fighter("Navajo Stirling", "Light Heavyweight", 78, 70, 72, 25),
    "Rodolfo Bellato": Fighter("Rodolfo Bellato", "Light Heavyweight", 80, 68, 85, 28),
    "Nicolae Negumereanu": Fighter("Nicolae Negumereanu", "Light Heavyweight", 77, 68, 70, 25),
    "Ibo Aslan": Fighter("Ibo Aslan", "Light Heavyweight", 83, 72, 65, 27),
    "Oumar Sy": Fighter("Oumar Sy", "Light Heavyweight", 79, 68, 82, 26),
    "Ozzy Diaz": Fighter("Ozzy Diaz", "Light Heavyweight", 77, 68, 70, 24),
    "Billy Elekana": Fighter("Billy Elekana", "Light Heavyweight", 76, 67, 69, 23),
    "Bruno Lopes": Fighter("Bruno Lopes", "Light Heavyweight", 81, 70, 68, 25),
    "Ryan Spann": Fighter("Ryan Spann", "Light Heavyweight", 83, 78, 75, 45),
    "Ion Cutelaba": Fighter("Ion Cutelaba", "Light Heavyweight", 88, 70, 70, 50),
    "Julius Walker": Fighter("Julius Walker", "Light Heavyweight", 77, 68, 70, 22),
    "Paul Craig": Fighter("Paul Craig", "Light Heavyweight", 80, 70, 88, 48),
    "Rafael Cerqueira": Fighter("Rafael Cerqueira", "Light Heavyweight", 79, 70, 80, 24),
    "Diyar Nurgozhay": Fighter("Diyar Nurgozhay", "Light Heavyweight", 76, 67, 69, 21),
    "Brendson Ribeiro": Fighter("Brendson Ribeiro", "Light Heavyweight", 82, 73, 65, 26),
    "Marcin Prachnio": Fighter("Marcin Prachnio", "Light Heavyweight", 80, 75, 60, 29),
    "Vitor Petrino": Fighter("Vitor Petrino", "Light Heavyweight", 86, 78, 70, 42),
    "Ivan Erslan": Fighter("Ivan Erslan", "Light Heavyweight", 87, 78, 70, 35),
    "Jimmy Crute": Fighter("Jimmy Crute", "Light Heavyweight", 84, 75, 80, 42),

    "Dricus Du Plessis": Fighter("Dricus Du Plessis", "Middleweight", 88, 82, 80, 90),
    "Nassourdine Imavov": Fighter("Nassourdine Imavov", "Middleweight", 85, 80, 75, 62),
    "Sean Strickland": Fighter("Sean Strickland", "Middleweight", 83, 75, 72, 92),
    "Khamzat Chimaev": Fighter("Khamzat Chimaev", "Middleweight", 90, 88, 90, 93),
    "Israel Adesanya": Fighter("Israel Adesanya", "Middleweight", 88, 95, 70, 95),
    "Robert Whittaker": Fighter("Robert Whittaker", "Middleweight", 85, 85, 78, 88),
    "Caio Borralho": Fighter("Caio Borralho", "Middleweight", 80, 78, 82, 50),
    "Jared Cannonier": Fighter("Jared Cannonier", "Middleweight", 86, 78, 77, 70),
    "Roman Dolidze": Fighter("Roman Dolidze", "Middleweight", 84, 75, 85, 60),
    "Anthony Hernandez": Fighter("Anthony Hernandez", "Middleweight", 80, 75, 85, 52),
    "Brendan Allen": Fighter("Brendan Allen", "Middleweight", 82, 78, 88, 65),
    "Marvin Vettori": Fighter("Marvin Vettori", "Middleweight", 83, 75, 82, 72),
    "Reinier de Ridder": Fighter("Reinier de Ridder", "Middleweight", 80, 72, 95, 70),
    "Paulo Costa": Fighter("Paulo Costa", "Middleweight", 90, 75, 70, 85),
    "Roman Kopylov": Fighter("Roman Kopylov", "Middleweight", 87, 80, 68, 50),
    "Abus Magomedov": Fighter("Abus Magomedov", "Middleweight", 86, 78, 70, 48),
    "Joe Pyfer": Fighter("Joe Pyfer", "Middleweight", 87, 78, 72, 50),
    "Nursulton Ruziboev": Fighter("Nursulton Ruziboev", "Middleweight", 89, 78, 70, 55),
    "Jack Hermansson": Fighter("Jack Hermansson", "Middleweight", 84, 75, 82, 60),
    "Michel Pereira": Fighter("Michel Pereira", "Middleweight", 85, 90, 75, 80),
    "Bo Nickal": Fighter("Bo Nickal", "Middleweight", 80, 80, 98, 85),
    "Gregory Rodrigues": Fighter("Gregory Rodrigues", "Middleweight", 86, 75, 78, 45),
    "Ikram Aliskerov": Fighter("Ikram Aliskerov", "Middleweight", 85, 77, 80, 55),
    "Michael Page": Fighter("Michael Page", "Middleweight", 90, 92, 60, 78),
    "Mansur Abdul-Malik": Fighter("Mansur Abdul-Malik", "Middleweight", 78, 70, 75, 25),
    "Kelvin Gastelum": Fighter("Kelvin Gastelum", "Middleweight", 85, 78, 75, 68),
    "Azamat Bekoev": Fighter("Azamat Bekoev", "Middleweight", 79, 68, 82, 26),
    "Brunno Ferreira": Fighter("Brunno Ferreira", "Middleweight", 86, 75, 70, 30),
    "Shara Magomedov": Fighter("Shara Magomedov", "Middleweight", 90, 85, 65, 75),
    "Jacob Malkoun": Fighter("Jacob Malkoun", "Middleweight", 78, 70, 78, 28),
    "Marco Tulio": Fighter("Marco Tulio", "Middleweight", 77, 68, 70, 22),
    "Cesar Almeida": Fighter("Cesar Almeida", "Middleweight", 85, 78, 60, 35),
    "Chris Curtis": Fighter("Chris Curtis", "Middleweight", 87, 75, 70, 60),
    "Ozzy Diaz": Fighter("Ozzy Diaz", "Middleweight", 77, 68, 70, 24),
    "Ateba Gautier": Fighter("Ateba Gautier", "Middleweight", 76, 67, 69, 20),
    "Rodolfo Vieira": Fighter("Rodolfo Vieira", "Middleweight", 75, 65, 95, 45),
    "Aliaskhab Khizriev": Fighter("Aliaskhab Khizriev", "Middleweight", 82, 75, 88, 30),
    "Torrez Finney": Fighter("Torrez Finney", "Middleweight", 75, 68, 70, 18),
    "Ismail Naurdiev": Fighter("Ismail Naurdiev", "Middleweight", 80, 75, 75, 28),
    "Edmen Shahbazyan": Fighter("Edmen Shahbazyan", "Middleweight", 85, 78, 65, 40),
    "JunYong Park": Fighter("JunYong Park", "Middleweight", 82, 78, 72, 35),
    "Christian Leroy Duncan": Fighter("Christian Leroy Duncan", "Middleweight", 85, 85, 65, 40),
    "Andre Petroski": Fighter("Andre Petroski", "Middleweight", 78, 70, 85, 30),
    "Cody Brundage": Fighter("Cody Brundage", "Middleweight", 77, 68, 80, 28),
    "Andre Muniz": Fighter("Andre Muniz", "Middleweight", 78, 70, 90, 55),
    "Paul Craig": Fighter("Paul Craig", "Middleweight", 78, 68, 85, 40),
    "Zachary Reese": Fighter("Zachary Reese", "Middleweight", 76, 67, 70, 20),
    "Eric McConico": Fighter("Eric McConico", "Middleweight", 75, 66, 68, 19),
    "Nick Klein": Fighter("Nick Klein", "Middleweight", 77, 69, 70, 20),
    "Tresean Gore": Fighter("Tresean Gore", "Middleweight", 83, 72, 75, 30),
    "Eryk Anders": Fighter("Eryk Anders", "Middleweight", 80, 70, 72, 32),
    "Robert Bryczek": Fighter("Robert Bryczek", "Middleweight", 86, 78, 65, 35),
    "Ryan Loder": Fighter("Ryan Loder", "Middleweight", 76, 67, 70, 20),
    "Nick Diaz": Fighter("Nick Diaz", "Middleweight", 80, 70, 70, 70),
    "Andrey Pulyaev": Fighter("Andrey Pulyaev", "Middleweight", 75, 66, 68, 19),
    "Michal Oleksiejczuk": Fighter("Michal Oleksiejczuk", "Middleweight", 87, 75, 60, 38),
    "Sedriques Dumas": Fighter("Sedriques Dumas", "Middleweight", 79, 75, 70, 30),
    "Kamaru Usman": Fighter("Kamaru Usman", "Middleweight", 85, 88, 92, 90),
    "Robert Valentin": Fighter("Robert Valentin", "Middleweight", 76, 67, 69, 19),
    "Antonio Trocoli": Fighter("Antonio Trocoli", "Middleweight", 77, 68, 80, 22),
    "Dustin Stoltzfus": Fighter("Dustin Stoltzfus", "Middleweight", 79, 70, 75, 25),
    "Gerald Meerschaert": Fighter("Gerald Meerschaert", "Middleweight", 80, 70, 78, 35),
    "Jose Daniel Medina": Fighter("Jose Daniel Medina", "Middleweight", 75, 66, 68, 18),
    "Marc-Andre Barriault": Fighter("Marc-Andre Barriault", "Middleweight", 82, 70, 70, 32),
    "Dusko Todorovic": Fighter("Dusko Todorovic", "Middleweight", 78, 70, 65, 25),

    "Jack Della Maddalena": Fighter("Jack Della Maddalena", "Welterweight", 87, 85, 75, 78),
    "Islam Makhachev": Fighter("Islam Makhachev", "Welterweight", 87, 85, 98, 95),
    "Belal Muhammad": Fighter("Belal Muhammad", "Welterweight", 82, 80, 88, 85),
    "Sean Brady": Fighter("Sean Brady", "Welterweight", 80, 75, 88, 60),
    "Shavkat Rakhmonov": Fighter("Shavkat Rakhmonov", "Welterweight", 89, 82, 85, 88),
    "Leon Edwards": Fighter("Leon Edwards", "Welterweight", 88, 88, 85, 92),
    "Kamaru Usman": Fighter("Kamaru Usman", "Welterweight", 90, 88, 95, 97),
    "Ian Machado Garry": Fighter("Ian Garry", "Welterweight", 85, 82, 70, 80),
    "Joaquin Buckley": Fighter("Joaquin Buckley", "Welterweight", 88, 80, 65, 70),
    "Michael Morales": Fighter("Michael Morales", "Welterweight", 86, 80, 70, 60),
    "Colby Covington": Fighter("Colby Covington", "Welterweight", 80, 85, 92, 85),
    "Gilbert Burns": Fighter("Gilbert Burns", "Welterweight", 88, 78, 90, 80),
    "Geoff Neal": Fighter("Geoff Neal", "Welterweight", 83, 80, 72, 58),
    "Stephen Thompson": Fighter("Stephen Thompson", "Welterweight", 85, 90, 70, 75),
    "Carlos Prates": Fighter("Carlos Prates", "Welterweight", 85, 82, 65, 45),
    "Kevin Holland": Fighter("Kevin Holland", "Welterweight", 80, 78, 70, 75),
    "Michael Page": Fighter("Michael Page", "Welterweight", 90, 92, 60, 78),
    "Gabriel Bonfim": Fighter("Gabriel Bonfim", "Welterweight", 82, 78, 80, 40),
    "Randy Brown": Fighter("Randy Brown", "Welterweight", 80, 78, 72, 42),
    "Rinat Fakhretdinov": Fighter("Rinat Fakhretdinov", "Welterweight", 80, 75, 85, 35),
    "Bryan Battle": Fighter("Bryan Battle", "Welterweight", 80, 72, 78, 30),
    "Neil Magny": Fighter("Neil Magny", "Welterweight", 80, 78, 75, 55),
    "Andreas Gustafsson": Fighter("Andreas Gustafsson", "Welterweight", 78, 70, 75, 25),
    "Vicente Luque": Fighter("Vicente Luque", "Welterweight", 85, 78, 80, 68),
    "Mike Malott": Fighter("Mike Malott", "Welterweight", 84, 78, 75, 52),
    "Michael Chiesa": Fighter("Michael Chiesa", "Welterweight", 82, 75, 85, 50),
    "Khaos Williams": Fighter("Khaos Williams", "Welterweight", 88, 75, 65, 55),
    "Sam Patterson": Fighter("Sam Patterson", "Welterweight", 79, 72, 68, 28),
    "Chidi Njokuani": Fighter("Chidi Njokuani", "Welterweight", 85, 75, 60, 35),
    "Trey Waters": Fighter("Trey Waters", "Welterweight", 82, 78, 65, 30),
    "Oban Elliott": Fighter("Oban Elliott", "Welterweight", 80, 75, 72, 32),
    "Daniel Rodriguez": Fighter("Daniel Rodriguez", "Welterweight", 83, 75, 68, 48),
    "Jake Matthews": Fighter("Jake Matthews", "Welterweight", 80, 72, 75, 38),
    "Punahele Soriano": Fighter("Punahele Soriano", "Welterweight", 87, 70, 70, 40),
    "Jonny Parsons": Fighter("Jonny Parsons", "Welterweight", 82, 75, 65, 28),
    "Nicolas Dalby": Fighter("Nicolas Dalby", "Welterweight", 80, 70, 75, 35),
    "Jacobe Smith": Fighter("Jacobe Smith", "Welterweight", 78, 70, 85, 25),
    "Jonathan Micallef": Fighter("Jonathan Micallef", "Welterweight", 76, 68, 70, 20),
    "Max Griffin": Fighter("Max Griffin", "Welterweight", 81, 75, 70, 32),
    "Gunnar Nelson": Fighter("Gunnar Nelson", "Welterweight", 78, 75, 88, 50),
    "Muslim Salikhov": Fighter("Muslim Salikhov", "Welterweight", 86, 75, 68, 38),
    "Li Jingliang": Fighter("Li Jingliang", "Welterweight", 83, 72, 75, 48),
    "Ramiz Brahimaj": Fighter("Ramiz Brahimaj", "Welterweight", 75, 68, 85, 28),
    "Adam Fugitt": Fighter("Adam Fugitt", "Welterweight", 79, 70, 72, 26),
    "Carlos Leal": Fighter("Carlos Leal", "Welterweight", 84, 75, 68, 30),
    "Gilbert Urbina": Fighter("Gilbert Urbina", "Welterweight", 78, 70, 80, 25),
    "Themba Gorimbo": Fighter("Themba Gorimbo", "Welterweight", 76, 68, 75, 30),
    "Charles Radtke": Fighter("Charles Radtke", "Welterweight", 80, 72, 65, 28),
    "Carlston Harris": Fighter("Carlston Harris", "Welterweight", 82, 70, 80, 32),
    "Uros Medic": Fighter("Uros Medic", "Welterweight", 84, 75, 60, 30),
    "Bassil Hafez": Fighter("Bassil Hafez", "Welterweight", 80, 70, 75, 28),
    "Elizeu Zaleski dos Santos": Fighter("Elizeu Zaleski dos Santos", "Welterweight", 83, 78, 70, 45),
    "Ismail Naurdiev": Fighter("Ismail Naurdiev", "Welterweight", 81, 75, 75, 28),
    "Lyman Good": Fighter("Lyman Good", "Welterweight", 80, 70, 70, 30),
    "Danny Barlow": Fighter("Danny Barlow", "Welterweight", 83, 78, 65, 30),
    "Evan Elder": Fighter("Evan Elder", "Welterweight", 78, 70, 72, 25),
    "Phil Rowe": Fighter("Phil Rowe", "Welterweight", 82, 75, 68, 32),
    "Santiago Ponzinibbio": Fighter("Santiago Ponzinibbio", "Welterweight", 84, 77, 70, 50),
    "Sheldon Westcott": Fighter("Sheldon Westcott", "Welterweight", 75, 65, 70, 20),
    "Jeremiah Wells": Fighter("Jeremiah Wells", "Welterweight", 82, 75, 78, 45),
    "Rhys McKee": Fighter("Rhys McKee", "Welterweight", 79, 72, 60, 25),
    "Daniel Frunza": Fighter("Daniel Frunza", "Welterweight", 76, 67, 69, 18),
    "Matt Brown": Fighter("Matt Brown", "Welterweight", 82, 70, 70, 50),
    "Gabe Green": Fighter("Gabe Green", "Welterweight", 79, 75, 68, 30),
    "Pete Rodriguez": Fighter("Pete Rodriguez", "Welterweight", 85, 78, 60, 30),
    "Francisco Prado": Fighter("Francisco Prado", "Welterweight", 80, 75, 70, 28),
    "Billy Ray Goff": Fighter("Billy Ray Goff", "Welterweight", 82, 75, 68, 28),
    "Rafael Dos Anjos": Fighter("Rafael dos Anjos", "Welterweight", 85, 78, 82, 70),
    "Niko Price": Fighter("Niko Price", "Welterweight", 85, 80, 70, 45),
    "Preston Parsons": Fighter("Preston Parsons", "Welterweight", 78, 70, 75, 28),
    "Rolando Bedoya": Fighter("Rolando Bedoya", "Welterweight", 78, 70, 75, 25),
    "Song Kenan": Fighter("Song Kenan", "Welterweight", 80, 72, 65, 30),
    "Kiefer Crosbie": Fighter("Kiefer Crosbie", "Welterweight", 79, 70, 60, 28),
    "Trevin Giles": Fighter("Trevin Giles", "Welterweight", 80, 75, 70, 35),
    "Ange Loosa": Fighter("Ange Loosa", "Welterweight", 78, 70, 72, 28),
    "Yusaku Kinoshita": Fighter("Yusaku Kinoshita", "Welterweight", 81, 75, 65, 25),
    "Wellington Turman": Fighter("Wellington Turman", "Welterweight", 77, 68, 80, 30),
    "Darrius Flowers": Fighter("Darrius Flowers", "Welterweight", 83, 70, 65, 28),
    "Tim Means": Fighter("Tim Means", "Welterweight", 80, 70, 70, 38),
    "Court McGee": Fighter("Court McGee", "Welterweight", 75, 65, 75, 30),
    "Mickey Gall": Fighter("Mickey Gall", "Welterweight", 75, 68, 80, 32),
    "Alex Morono": Fighter("Alex Morono", "Welterweight", 82, 75, 70, 40),

    "Ilia Topuria": Fighter("Ilia Topuria", "Lightweight", 90, 88, 85, 95),
    "Arman Tsarukyan": Fighter("Arman Tsarukyan", "Lightweight", 85, 82, 88, 88),
    "Charles Oliveira": Fighter("Charles Oliveira", "Lightweight", 88, 85, 92, 90),
    "Justin Gaethje": Fighter("Justin Gaethje", "Lightweight", 90, 85, 70, 92),
    "Max Holloway": Fighter("Max Holloway", "Lightweight", 88, 92, 70, 93),
    "Dustin Poirier": Fighter("Dustin Poirier", "Lightweight", 87, 83, 75, 89),
    "Dan Hooker": Fighter("Dan Hooker", "Lightweight", 83, 80, 75, 70),
    "Mateusz Gamrot": Fighter("Mateusz Gamrot", "Lightweight", 82, 78, 85, 70),
    "Paddy Pimblett": Fighter("Paddy Pimblett", "Lightweight", 80, 75, 80, 90),
    "Beneil Dariush": Fighter("Beneil Dariush", "Lightweight", 83, 80, 87, 75),
    "Renato Moicano": Fighter("Renato Moicano", "Lightweight", 80, 78, 88, 65),
    "Rafael Fiziev": Fighter("Rafael Fiziev", "Lightweight", 87, 88, 70, 78),
    "Michael Chandler": Fighter("Michael Chandler", "Lightweight", 88, 82, 72, 85),
    "Benoit Saint Denis": Fighter("Benoit Saint-Denis", "Lightweight", 87, 80, 85, 80),
    "Grant Dawson": Fighter("Grant Dawson", "Lightweight", 78, 75, 90, 60),
    "Joel Alvarez": Fighter("Joel Alvarez", "Lightweight", 83, 78, 80, 42),
    "Ignacio Bahamondes": Fighter("Ignacio Bahamondes", "Lightweight", 85, 80, 68, 50),
    "Mauricio Ruffy": Fighter("Mauricio Ruffy", "Lightweight", 83, 78, 68, 30),
    "Fares Ziam": Fighter("Fares Ziam", "Lightweight", 80, 75, 70, 32),
    "Nasrat Haqparast": Fighter("Nasrat Haqparast", "Lightweight", 82, 78, 65, 38),
    "Chase Hooper": Fighter("Chase Hooper", "Lightweight", 75, 70, 88, 40),
    "King Green": Fighter("Bobby Green", "Lightweight", 80, 85, 70, 72),
    "Ludovit Klein": Fighter("Ludovit Klein", "Lightweight", 80, 78, 72, 35),
    "Mateusz Rebecki": Fighter("Mateusz Rebecki", "Lightweight", 85, 78, 75, 38),
    "Nazim Sadykhov": Fighter("Nazim Sadykhov", "Lightweight", 82, 78, 68, 35),
    "Manuel Torres": Fighter("Manuel Torres", "Lightweight", 84, 78, 65, 35),
    "Rafael Dos Anjos": Fighter("Rafael dos Anjos", "Lightweight", 86, 80, 85, 70),
    "Jared Gordon": Fighter("Jared Gordon", "Lightweight", 80, 72, 75, 40),
    "Chris Duncan": Fighter("Chris Duncan", "Lightweight", 83, 75, 68, 30),
    "Chris Padilla": Fighter("Chris Padilla", "Lightweight", 76, 68, 70, 20),
    "MarQuel Mederos": Fighter("MarQuel Mederos", "Lightweight", 75, 67, 69, 18),
    "Drakkar Klose": Fighter("Drakkar Klose", "Lightweight", 80, 75, 78, 42),
    "Jim Miller": Fighter("Jim Miller", "Lightweight", 78, 70, 85, 60),
    "Esteban Ribovics": Fighter("Esteban Ribovics", "Lightweight", 82, 78, 65, 30),
    "Charlie Campbell": Fighter("Charlie Campbell", "Lightweight", 83, 75, 60, 28),
    "Myktybek Orolbai": Fighter("Myktybek Orolbai", "Lightweight", 80, 72, 85, 35),
    "Mike Davis": Fighter("Mike Davis", "Lightweight", 82, 78, 68, 38),
    "Quillan Salkilld": Fighter("Quillan Salkilld", "Lightweight", 75, 66, 68, 18),
    "Nurullo Aliev": Fighter("Nurullo Aliev", "Lightweight", 78, 70, 85, 30),
    "Ismael Bonfim": Fighter("Ismael Bonfim", "Lightweight", 85, 80, 70, 35),
    "Nikolas Motta": Fighter("Nikolas Motta", "Lightweight", 84, 75, 65, 32),
    "Matt Frevola": Fighter("Matt Frevola", "Lightweight", 80, 72, 75, 40),
    "Daniel Zellhuber": Fighter("Daniel Zellhuber", "Lightweight", 82, 78, 68, 35),
    "Gabe Green": Fighter("Gabe Green", "Lightweight", 80, 75, 68, 30),
    "Francis Marshall": Fighter("Francis Marshall", "Lightweight", 79, 72, 75, 28),
    "Alexander Hernandez": Fighter("Alexander Hernandez", "Lightweight", 82, 80, 75, 48),
    "Thiago Moises": Fighter("Thiago Moises", "Lightweight", 78, 70, 85, 45),
    "Diego Ferreira": Fighter("Carlos Diego Ferreira", "Lightweight", 79, 75, 82, 45),
    "Rafa Garcia": Fighter("Rafa Garcia", "Lightweight", 78, 72, 80, 30),
    "Evan Elder": Fighter("Evan Elder", "Lightweight", 78, 70, 72, 25),
    "Francisco Prado": Fighter("Francisco Prado", "Lightweight", 80, 75, 70, 28),
    "David Teymur": Fighter("David Teymur", "Lightweight", 80, 78, 65, 30),
    "Tom Nolan": Fighter("Tom Nolan", "Lightweight", 83, 75, 60, 28),
    "Kaue Fernandes": Fighter("Kaue Fernandes", "Lightweight", 77, 68, 70, 20),
    "Jordan Leavitt": Fighter("Jordan Leavitt", "Lightweight", 75, 68, 85, 30),
    "Mason Jones": Fighter("Mason Jones", "Lightweight", 80, 72, 75, 32),
    "Bolaji Oki": Fighter("Bolaji Oki", "Lightweight", 84, 75, 65, 30),
    "Mark Choinski": Fighter("Mark Choinski", "Lightweight", 76, 67, 69, 18),
    "AJ Cunningham": Fighter("AJ Cunningham", "Lightweight", 75, 66, 68, 18),
    "Mitch Ramirez": Fighter("Mitch Ramirez", "Lightweight", 77, 69, 70, 20),
    "Trey Ogden": Fighter("Trey Ogden", "Lightweight", 76, 68, 80, 25),
    "David Onama": Fighter("David Onama", "Lightweight", 85, 80, 68, 35),
    "Yanal Ashmouz": Fighter("Yanal Ashmouz", "Lightweight", 78, 70, 82, 28),
    "Dennis Buzukja": Fighter("Dennis Buzukja", "Lightweight", 80, 75, 65, 30),
    "Michael Johnson": Fighter("Michael Johnson", "Lightweight", 80, 82, 65, 45),
    "Joe Lauzon": Fighter("Joe Lauzon", "Lightweight", 75, 68, 80, 35),
    "Matheus Camilo": Fighter("Matheus Camilo", "Lightweight", 76, 67, 69, 18),
    "Elves Brener": Fighter("Elves Brener", "Lightweight", 79, 75, 78, 30),
    "Rongzhu": Fighter("Rongzhu", "Lightweight", 78, 70, 65, 25),
    "Terrance McKinney": Fighter("Terrance McKinney", "Lightweight", 85, 88, 70, 38),
    "Vagner Rocha": Fighter("Vagner Rocha", "Lightweight", 75, 65, 85, 28),
    "Kody Steele": Fighter("Kody Steele", "Lightweight", 76, 67, 69, 18),
    "Gauge Young": Fighter("Gauge Young", "Lightweight", 75, 66, 68, 18),
    "Roberto Romero": Fighter("Roberto Romero", "Lightweight", 77, 69, 70, 20),
    "Abdul-Kareem Al-Selwady": Fighter("Abdul-Kareem Al-Selwady", "Lightweight", 79, 70, 75, 25),
    "Jai Herbert": Fighter("Jai Herbert", "Lightweight", 80, 75, 65, 30),
    "Darrius Flowers": Fighter("Darrius Flowers", "Lightweight", 83, 70, 65, 28),
    "Loik Radzhabov": Fighter("Loik Radzhabov", "Lightweight", 78, 70, 82, 32),
    "Claudio Puelles": Fighter("Claudio Puelles", "Lightweight", 75, 65, 90, 30),
    "Anshul Jubli": Fighter("Anshul Jubli", "Lightweight", 80, 75, 68, 30),
    "Viacheslav Borshchev": Fighter("Viacheslav Borshchev", "Lightweight", 84, 78, 60, 32),
    "Trevor Peek": Fighter("Trevor Peek", "Lightweight", 86, 75, 65, 35),
    "Joaquim Silva": Fighter("Joaquim Silva", "Lightweight", 80, 75, 68, 30),
    "Damir Hadzovic": Fighter("Damir Hadzovic", "Lightweight", 78, 70, 65, 28),
    "Austin Hubbard": Fighter("Austin Hubbard", "Lightweight", 78, 70, 75, 30),
    "Al Iaquinta": Fighter("Al Iaquinta", "Lightweight", 80, 72, 70, 45),
    "Brad Riddell": Fighter("Brad Riddell", "Lightweight", 82, 78, 65, 38),
    "Kurt Holobaugh": Fighter("Kurt Holobaugh", "Lightweight", 77, 70, 72, 28),
    "Alex Reyes": Fighter("Alex Reyes", "Lightweight", 76, 67, 69, 20),
    "Rolando Bedoya": Fighter("Rolando Bedoya", "Lightweight", 78, 70, 75, 25),
    "Mohammad Yahya": Fighter("Mohammad Yahya", "Lightweight", 80, 75, 60, 25),
    "Jordan Vucenic": Fighter("Jordan Vucenic", "Lightweight", 77, 70, 80, 28),
    "Jamie Mullarkey": Fighter("Jamie Mullarkey", "Lightweight", 80, 72, 70, 32),
    "Lando Vannata": Fighter("Lando Vannata", "Lightweight", 80, 80, 68, 40),
    "Maheshate": Fighter("Maheshate", "Lightweight", 82, 75, 60, 28),
    "Victor Martinez": Fighter("Victor Martinez", "Lightweight", 78, 70, 65, 25),
    "Drew Dober": Fighter("Drew Dober", "Lightweight", 88, 78, 68, 65),
    "Ottman Azaitar": Fighter("Ottman Azaitar", "Lightweight", 86, 78, 60, 35),
    "Kyle Prepolec": Fighter("Kyle Prepolec", "Lightweight", 75, 66, 68, 18),
    "Jeremy Stephens": Fighter("Jeremy Stephens", "Lightweight", 80, 70, 65, 45),

    "Alexander Volkanovski": Fighter("Alexander Volkanovski", "Featherweight", 90, 90, 80, 92),
    "Max Holloway": Fighter("Max Holloway", "Featherweight", 85, 88, 78, 90),
    "Diego Lopes": Fighter("Diego Lopes", "Featherweight", 85, 80, 87, 80),
    "Movsar Evloev": Fighter("Movsar Evloev", "Featherweight", 83, 82, 88, 70),
    "Aaron Pico": Fighter("Aaron Pico", "Featherweight", 83, 75, 75, 61),
    "Yair Rodriguez": Fighter("Yair Rodríguez", "Featherweight", 83, 90, 71, 78),
    "Arnold Allen": Fighter("Arnold Allen", "Featherweight", 80, 85, 80, 75),
    "Brian Ortega": Fighter("Brian Ortega", "Featherweight", 80, 80, 92, 80),
    "Lerone Murphy": Fighter("Lerone Murphy", "Featherweight", 82, 85, 75, 55),
    "Aljamain Sterling": Fighter("Aljamain Sterling", "Featherweight", 85, 82, 90, 85),
    "Josh Emmett": Fighter("Josh Emmett", "Featherweight", 87, 80, 78, 65),
    "Jean Silva": Fighter("Jean Silva", "Featherweight", 80, 78, 70, 30),
    "Youssef Zalal": Fighter("Youssef Zalal", "Featherweight", 78, 80, 68, 28),
    "David Onama": Fighter("David Onama", "Featherweight", 85, 78, 70, 40),
    "Dan Ige": Fighter("Dan Ige", "Featherweight", 80, 78, 78, 50),
    "Calvin Kattar": Fighter("Calvin Kattar", "Featherweight", 82, 80, 70, 68),
    "Hyder Amil": Fighter("Hyder Amil", "Featherweight", 76, 70, 68, 22),
    "William Gomis": Fighter("William Gomis", "Featherweight", 80, 82, 65, 30),
    "Bryce Mitchell": Fighter("Bryce Mitchell", "Featherweight", 80, 78, 90, 55),
    "Patricio Pitbull": Fighter("Patricio Pitbull", "Featherweight", 76, 83, 61, 65),
    "Chepe Mariscal": Fighter("Chepe Mariscal", "Featherweight", 79, 72, 75, 28),
    "Steve Garcia": Fighter("Steve Garcia", "Featherweight", 80, 75, 68, 30),
    "Pat Sabatini": Fighter("Pat Sabatini", "Featherweight", 78, 72, 85, 28),
    "Edson Barboza": Fighter("Edson Barboza", "Featherweight", 88, 90, 65, 72),
    "Felipe Lima": Fighter("Felipe Lima", "Featherweight", 82, 78, 70, 25),
    "Melquizael Costa": Fighter("Melquizael Costa", "Featherweight", 78, 75, 75, 28),
    "Giga Chikadze": Fighter("Giga Chikadze", "Featherweight", 86, 88, 70, 70),
    "Mairon Santos": Fighter("Mairon Santos", "Featherweight", 75, 68, 70, 20),
    "Nathaniel Wood": Fighter("Nathaniel Wood", "Featherweight", 80, 78, 72, 40),
    "Danny Silva": Fighter("Danny Silva", "Featherweight", 76, 69, 70, 22),
    "Sean Woodson": Fighter("Sean Woodson", "Featherweight", 83, 80, 65, 35),
    "Dooho Choi": Fighter("Dooho Choi", "Featherweight", 85, 78, 65, 40),
    "Ryan Hall": Fighter("Ryan Hall", "Featherweight", 70, 65, 95, 35),
    "Bogdan Grad": Fighter("Bogdan Grad", "Featherweight", 75, 68, 70, 20),
    "Nathan Fletcher": Fighter("Nathan Fletcher", "Featherweight", 77, 70, 80, 25),
    "Nate Landwehr": Fighter("Nate Landwehr", "Featherweight", 82, 70, 75, 42),
    "Joanderson Brito": Fighter("Joanderson Brito", "Featherweight", 83, 80, 78, 35),
    "Daniel Santos": Fighter("Daniel Santos", "Featherweight", 80, 75, 68, 30),
    "JooSang Yoo": Fighter("JooSang Yoo", "Featherweight", 76, 69, 70, 20),
    "Jose Delgado": Fighter("Jose Delgado", "Featherweight", 75, 68, 69, 18),
    "Kevin Vallejos": Fighter("Kevin Vallejos", "Featherweight", 75, 68, 69, 18),
    "Kyle Nelson": Fighter("Kyle Nelson", "Featherweight", 77, 70, 70, 25),
    "Cub Swanson": Fighter("Cub Swanson", "Featherweight", 82, 78, 70, 50),
    "Morgan Charriere": Fighter("Morgan Charriere", "Featherweight", 80, 75, 68, 30),
    "Jamall Emmers": Fighter("Jamall Emmers", "Featherweight", 80, 80, 75, 35),
    "Isaac Dulgarian": Fighter("Isaac Dulgarian", "Featherweight", 78, 70, 85, 28),
    "Gabriel Santos": Fighter("Gabriel Santos", "Featherweight", 80, 75, 80, 32),
    "Melsik Baghdasaryan": Fighter("Melsik Baghdasaryan", "Featherweight", 83, 78, 60, 35),
    "Miles Johns": Fighter("Miles Johns", "Featherweight", 80, 75, 75, 38),
    "Patricio Freire": Fighter("Patricio Freire", "Featherweight", 88, 85, 80, 90),
    "Andre Fili": Fighter("Andre Fili", "Featherweight", 79, 78, 70, 40),
    "Julian Erosa": Fighter("Julian Erosa", "Featherweight", 79, 75, 70, 38),
    "Westin Wilson": Fighter("Westin Wilson", "Featherweight", 77, 70, 72, 25),
    "Fernando Padilla": Fighter("Fernando Padilla", "Featherweight", 80, 78, 68, 30),
    "Christian Rodriguez": Fighter("Christian Rodriguez", "Featherweight", 79, 75, 72, 35),
    "Vagner Rocha": Fighter("Vagner Rocha", "Featherweight", 75, 68, 85, 28),
    "Manolo Zecchini": Fighter("Manolo Zecchini", "Featherweight", 75, 66, 68, 18),
    "Lando Vannata": Fighter("Lando Vannata", "Featherweight", 80, 80, 68, 40),
    "Steven Nguyen": Fighter("Steven Nguyen", "Featherweight", 82, 78, 65, 30),
    "Dennis Buzukja": Fighter("Dennis Buzukja", "Featherweight", 80, 75, 65, 30),
    "Jack Jenkins": Fighter("Jack Jenkins", "Featherweight", 78, 70, 80, 32),
    "Alex Caceres": Fighter("Alex Caceres", "Featherweight", 78, 82, 72, 45),
    "Francis Marshall": Fighter("Francis Marshall", "Featherweight", 79, 72, 75, 28),
    "Darren Elkins": Fighter("Darren Elkins", "Featherweight", 78, 70, 78, 40),
    "Lucas Almeida": Fighter("Lucas Almeida", "Featherweight", 82, 75, 68, 32),
    "Timmy Cuamba": Fighter("Timmy Cuamba", "Featherweight", 79, 75, 68, 25),
    "John Castaneda": Fighter("John Castaneda", "Featherweight", 80, 75, 75, 38),
    "Sodiq Yusuff": Fighter("Sodiq Yusuff", "Featherweight", 80, 85, 70, 60),
    "Billy Quarantillo": Fighter("Billy Quarantillo", "Featherweight", 78, 72, 75, 33),
    "JeongYeong Lee": Fighter("JeongYeong Lee", "Featherweight", 80, 78, 65, 28),
    "Kaan Ofli": Fighter("Kaan Ofli", "Featherweight", 75, 67, 69, 18),
    "Charles Jourdain": Fighter("Charles Jourdain", "Featherweight", 83, 80, 68, 45),
    "Shayilan Nuerdanbieke": Fighter("Shayilan Nuerdanbieke", "Featherweight", 78, 70, 80, 25),
    "Gavin Tucker": Fighter("Gavin Tucker", "Featherweight", 79, 75, 75, 30),
    "Yizha": Fighter("Yizha", "Featherweight", 75, 68, 70, 20),
    "Ricardo Ramos": Fighter("Ricardo Ramos", "Featherweight", 80, 78, 75, 35),
    "Erik Silva": Fighter("Erik Silva", "Featherweight", 76, 68, 70, 22),
    "Roberto Romero": Fighter("Roberto Romero", "Featherweight", 77, 69, 70, 20),

    "Merab Dvalishvili": Fighter("Merab Dvalishvili", "Bantamweight", 80, 85, 92, 90),
    "Sean O'Malley": Fighter("Sean O'Malley", "Bantamweight", 85, 92, 68, 98),
    "Umar Nurmagomedov": Fighter("Umar Nurmagomedov", "Bantamweight", 80, 82, 85, 78),
    "Petr Yan": Fighter("Petr Yan", "Bantamweight", 85, 80, 85, 80),
    "Cory Sandhagen": Fighter("Cory Sandhagen", "Bantamweight", 82, 85, 78, 82),
    "Song Yadong": Fighter("Song Yadong", "Bantamweight", 85, 83, 75, 70),
    "Deiveson Figueiredo": Fighter("Deiveson Figueiredo", "Bantamweight", 88, 80, 85, 80),
    "Marlon Vera": Fighter("Marlon Vera", "Bantamweight", 83, 80, 80, 78),
    "Rob Font": Fighter("Rob Font", "Bantamweight", 83, 80, 70, 65),
    "Mario Bautista": Fighter("Mario Bautista", "Bantamweight", 79, 80, 75, 50),
    "Henry Cejudo": Fighter("Henry Cejudo", "Bantamweight", 75, 78, 90, 85),
    "Aiemann Zahabi": Fighter("Aiemann Zahabi", "Bantamweight", 78, 75, 68, 30),
    "Kyler Phillips": Fighter("Kyler Phillips", "Bantamweight", 80, 82, 78, 55),
    "Marcus McGhee": Fighter("Marcus McGhee", "Bantamweight", 80, 78, 65, 32),
    "Montel Jackson": Fighter("Montel Jackson", "Bantamweight", 79, 80, 75, 48),
    "Vinicius Oliveira": Fighter("Vinicius Oliveira", "Bantamweight", 80, 82, 68, 28),
    "Raoni Barcelos": Fighter("Raoni Barcelos", "Bantamweight", 80, 78, 75, 40),
    "Chris Gutierrez": Fighter("Chris Gutierrez", "Bantamweight", 82, 80, 70, 50),
    "Jonathan Martinez": Fighter("Jonathan Martinez", "Bantamweight", 82, 80, 72, 62),
    "Daniel Marcos": Fighter("Daniel Marcos", "Bantamweight", 80, 83, 68, 50),
    "Farid Basharat": Fighter("Farid Basharat", "Bantamweight", 77, 78, 80, 35),
    "Raul Rosas Jr.": Fighter("Raul Rosas Jr.", "Bantamweight", 78, 80, 85, 70),
    "Said Nurmagomedov": Fighter("Said Nurmagomedov", "Bantamweight", 84, 85, 70, 65),
    "Charles Jourdain": Fighter("Charles Jourdain", "Bantamweight", 80, 78, 65, 40),
    "Brady Hiestand": Fighter("Brady Hiestand", "Bantamweight", 75, 70, 80, 28),
    "Payton Talbott": Fighter("Payton Talbott", "Bantamweight", 82, 85, 65, 45),
    "SuYoung You": Fighter("SuYoung You", "Bantamweight", 75, 70, 68, 20),
    "Tim Elliott": Fighter("Tim Elliott", "Bantamweight", 75, 78, 78, 40),
    "Cody Garbrandt": Fighter("Cody Garbrandt", "Bantamweight", 88, 85, 65, 75),
    "ChangHo Lee": Fighter("ChangHo Lee", "Bantamweight", 76, 70, 68, 22),
    "Muin Gafurov": Fighter("Muin Gafurov", "Bantamweight", 80, 75, 75, 30),
    "Malcolm Wellmaker": Fighter("Malcolm Wellmaker", "Bantamweight", 75, 68, 70, 18),
    "Miles Johns": Fighter("Miles Johns", "Bantamweight", 77, 75, 70, 30),
    "Da'Mon Blackshear": Fighter("Da'Mon Blackshear", "Bantamweight", 78, 75, 78, 35),
    "Rinya Nakamura": Fighter("Rinya Nakamura", "Bantamweight", 85, 80, 85, 45),
    "Serhiy Sidey": Fighter("Serhiy Sidey", "Bantamweight", 79, 78, 68, 30),
    "Jean Matsumoto": Fighter("Jean Matsumoto", "Bantamweight", 78, 72, 80, 28),
    "Daniel Santos": Fighter("Daniel Santos", "Bantamweight", 79, 75, 68, 30),
    "David Martinez": Fighter("David Martinez", "Bantamweight", 76, 70, 68, 20),
    "Aleksandre Topuria": Fighter("Aleksandre Topuria", "Bantamweight", 78, 75, 78, 30),
    "Adrian Yanez": Fighter("Adrian Yanez", "Bantamweight", 82, 82, 70, 60),
    "Cody Haddon": Fighter("Cody Haddon", "Bantamweight", 75, 68, 70, 18),
    "Elijah Smith": Fighter("Elijah Smith", "Bantamweight", 76, 69, 70, 20),
    "John Castaneda": Fighter("John Castaneda", "Bantamweight", 78, 75, 72, 35),
    "Davey Grant": Fighter("Davey Grant", "Bantamweight", 78, 75, 70, 32),
    "Victor Henry": Fighter("Victor Henry", "Bantamweight", 78, 78, 75, 45),
    "Carlos Vera": Fighter("Carlos Vera", "Bantamweight", 77, 72, 70, 25),
    "Bekzat Almakhan": Fighter("Bekzat Almakhan", "Bantamweight", 80, 78, 65, 28),
    "Benardo Sopaj": Fighter("Benardo Sopaj", "Bantamweight", 75, 68, 70, 18),
    "Alatengheili": Fighter("Alatengheili", "Bantamweight", 80, 75, 78, 35),
    "Pedro Munhoz": Fighter("Pedro Munhoz", "Bantamweight", 80, 75, 78, 55),
    "Xiao Long": Fighter("Xiao Long", "Bantamweight", 75, 67, 69, 18),
    "Patchy Mix": Fighter("Patchy Mix", "Bantamweight", 82, 80, 90, 80),
    "Aoriqileng": Fighter("Aoriqileng", "Bantamweight", 80, 75, 70, 30),
    "Ricky Simon": Fighter("Ricky Simon", "Bantamweight", 78, 78, 85, 50),
    "Quang Le": Fighter("Quang Le", "Bantamweight", 80, 78, 60, 25),
    "AJ Cunningham": Fighter("AJ Cunningham", "Bantamweight", 75, 68, 70, 18),
    "Colby Thicknesse": Fighter("Colby Thicknesse", "Bantamweight", 74, 67, 69, 18),
    "Baergeng Jieleyisi": Fighter("Baergeng Jieleyisi", "Bantamweight", 75, 68, 70, 18),
    "Gaston Bolanos": Fighter("Gaston Bolanos", "Bantamweight", 78, 75, 60, 25),
    "Ramon Taveras": Fighter("Ramon Taveras", "Bantamweight", 80, 78, 65, 28),
    "Douglas Silva de Andrade": Fighter("Douglas Silva de Andrade", "Bantamweight", 82, 78, 70, 40),
    "Steven Koslow": Fighter("Steven Koslow", "Bantamweight", 75, 68, 80, 25),
    "Nathan Fletcher": Fighter("Nathan Fletcher", "Bantamweight", 75, 68, 80, 25),
    "Angel Pacheco": Fighter("Angel Pacheco", "Bantamweight", 75, 67, 69, 18),
    "Josias Musasa": Fighter("Josias Musasa", "Bantamweight", 75, 68, 70, 18),
    "Toshiomi Kazama": Fighter("Toshiomi Kazama", "Bantamweight", 76, 70, 70, 20),
    "Frankie Saenz": Fighter("Frankie Saenz", "Bantamweight", 77, 72, 72, 30),
    "Rani Yahya": Fighter("Rani Yahya", "Bantamweight", 70, 65, 90, 30),
    "Matt Schnell": Fighter("Matt Schnell", "Bantamweight", 79, 78, 75, 40),
    "Ricky Turcios": Fighter("Ricky Turcios", "Bantamweight", 78, 75, 70, 30),
    "Cristian Quinonez": Fighter("Cristian Quinonez", "Bantamweight", 79, 78, 65, 30),
    "Javid Basharat": Fighter("Javid Basharat", "Bantamweight", 78, 80, 78, 40),
    "Chad Anheliger": Fighter("Chad Anheliger", "Bantamweight", 77, 72, 70, 28),
    "Cody Gibson": Fighter("Cody Gibson", "Bantamweight", 79, 75, 68, 30),
    "Brad Katona": Fighter("Brad Katona", "Bantamweight", 78, 75, 75, 35),
    "Garrett Armfield": Fighter("Garrett Armfield", "Bantamweight", 76, 70, 78, 25),
    "Luan Lacerda": Fighter("Luan Lacerda", "Bantamweight", 75, 68, 80, 25),
    "Cameron Smotherman": Fighter("Cameron Smotherman", "Bantamweight", 75, 68, 70, 18),
    "Kris Moutinho": Fighter("Kris Moutinho", "Bantamweight", 78, 70, 68, 28),
    "Saimon Oliveira": Fighter("Saimon Oliveira", "Bantamweight", 78, 75, 65, 28),
    "Cameron Saaiman": Fighter("Cameron Saaiman", "Bantamweight", 80, 82, 70, 45),
    "Vince Morales": Fighter("Vince Morales", "Bantamweight", 78, 75, 65, 30),

    "Alexandre Pantoja": Fighter("Alexandre Pantoja", "Flyweight", 85, 85, 90, 88),
    "Brandon Moreno": Fighter("Brandon Moreno", "Flyweight", 83, 80, 85, 85),
    "Brandon Royval": Fighter("Brandon Royval", "Flyweight", 82, 88, 82, 75),
    "Manel Kape": Fighter("Manel Kape", "Flyweight", 85, 88, 70, 72),
    "Amir Albazi": Fighter("Amir Albazi", "Flyweight", 80, 80, 88, 70),
    "Ramazan Temirov": Fighter("Ramazan Temirov", "Flyweight", 78, 75, 78, 25),
    "Tatsuro Taira": Fighter("Tatsuro Taira", "Flyweight", 78, 80, 85, 68),
    "Kai Kara-France": Fighter("Kai Kara-France", "Flyweight", 82, 85, 75, 68),
    "Joshua Van": Fighter("Joshua Van", "Flyweight", 78, 80, 70, 30),
    "Tagir Ulanbekov": Fighter("Tagir Ulanbekov", "Flyweight", 78, 78, 85, 50),
    "Allan Nascimento": Fighter("Allan Nascimento", "Flyweight", 75, 78, 85, 40),
    "Andre Lima": Fighter("Andre Lima", "Flyweight", 80, 82, 70, 30),
    "HyunSung Park": Fighter("HyunSung Park", "Flyweight", 77, 78, 70, 28),
    "Charles Johnson": Fighter("Charles Johnson", "Flyweight", 78, 75, 70, 28),
    "Rafael Estevam": Fighter("Rafael Estevam", "Flyweight", 79, 75, 75, 28),
    "Lone'er Kavanagh": Fighter("Lone'er Kavanagh", "Flyweight", 76, 78, 68, 25),
    "Asu Almabayev": Fighter("Asu Almabayev", "Flyweight", 77, 75, 82, 35),
    "Clayton Carpenter": Fighter("Clayton Carpenter", "Flyweight", 75, 75, 75, 22),
    "DongHun Choi": Fighter("DongHun Choi", "Flyweight", 75, 70, 68, 20),
    "Tim Elliott": Fighter("Tim Elliott", "Flyweight", 75, 75, 78, 40),
    "Alessandro Costa": Fighter("Alessandro Costa", "Flyweight", 78, 75, 72, 30),
    "Edgar Chairez": Fighter("Edgar Chairez", "Flyweight", 77, 75, 70, 25),
    "Jafel Filho": Fighter("Jafel Filho", "Flyweight", 79, 72, 80, 32),
    "Felipe Bunes": Fighter("Felipe Bunes", "Flyweight", 78, 80, 75, 32),
    "Kevin Borjas": Fighter("Kevin Borjas", "Flyweight", 80, 78, 65, 30),
    "Rei Tsuruya": Fighter("Rei Tsuruya", "Flyweight", 78, 80, 75, 30),
    "Kai Asakura": Fighter("Kai Asakura", "Flyweight", 85, 88, 75, 70),
    "Jose Ochoa": Fighter("Jose Ochoa", "Flyweight", 75, 68, 70, 18),
    "Jesus Aguilar": Fighter("Jesus Aguilar", "Flyweight", 76, 70, 78, 25),
    "Stewart Nicoll": Fighter("Stewart Nicoll", "Flyweight", 75, 68, 70, 18),
    "Lucas Rocha": Fighter("Lucas Rocha", "Flyweight", 77, 72, 75, 20),
    "Matt Schnell": Fighter("Matt Schnell", "Flyweight", 78, 78, 75, 45),
    "Azat Maksum": Fighter("Azat Maksum", "Flyweight", 78, 75, 80, 35),
    "SeungGuk Choi": Fighter("SeungGuk Choi", "Flyweight", 77, 75, 70, 28),
    "Alex Perez": Fighter("Alex Perez", "Flyweight", 80, 80, 75, 60),
    "Ronaldo Rodriguez": Fighter("Ronaldo Rodriguez", "Flyweight", 76, 70, 70, 20),
    "Kiru Sahota": Fighter("Kiru Sahota", "Flyweight", 75, 68, 68, 18),
    "Nyamjargal Tumendemberel": Fighter("Nyamjargal Tumendemberel", "Flyweight", 76, 72, 70, 20),
    "Ode Osbourne": Fighter("Ode Osbourne", "Flyweight", 80, 85, 65, 40),
    "Daniel Barez": Fighter("Daniel Barez", "Flyweight", 78, 75, 70, 28),
    "Sumudaerji": Fighter("Sumudaerji", "Flyweight", 85, 85, 65, 50),
    "Luis Gurule": Fighter("Luis Gurule", "Flyweight", 75, 68, 70, 18),
    "Felipe dos Santos": Fighter("Felipe dos Santos", "Flyweight", 79, 78, 70, 30),
    "Mitch Raposo": Fighter("Mitch Raposo", "Flyweight", 76, 70, 75, 25),
    "Steve Erceg": Fighter("Steve Erceg", "Flyweight", 80, 82, 80, 65),
    "Cody Durden": Fighter("Cody Durden", "Flyweight", 78, 75, 80, 38),

    "Valentina Shevchenko": Fighter("Valentina Shevchenko", "Women's Flyweight", 85, 88, 90, 65),
    "Natalia Silva": Fighter("Natalia Silva", "Women's Flyweight", 80, 85, 82, 45),
    "Manon Fiorot": Fighter("Manon Fiorot", "Women's Flyweight", 83, 85, 78, 46),
    "Alexa Grasso": Fighter("Alexa Grasso", "Women's Flyweight", 80, 82, 85, 67),
    "Erin Blanchfield": Fighter("Erin Blanchfield", "Women's Flyweight", 78, 80, 92, 48),
    "Maycee Barber": Fighter("Maycee Barber", "Women's Flyweight", 80, 78, 80, 75),
    "Jasmine Jasudavicius": Fighter("Jasmine Jasudavicius", "Women's Flyweight", 75, 70, 85, 23),
    "Rose Namajunas": Fighter("Rose Namajunas", "Women's Flyweight", 78, 85, 75, 70),
    "Viviane Araujo": Fighter("Viviane Araujo", "Women's Flyweight", 76, 75, 80, 38),
    "Jessica Andrade": Fighter("Jessica Andrade", "Women's Flyweight", 85, 80, 85, 29),
    "Tracy Cortez": Fighter("Tracy Cortez", "Women's Flyweight", 75, 72, 80, 49),
    "Miranda Maverick": Fighter("Miranda Maverick", "Women's Flyweight", 74, 72, 78, 39),
    "Karine Silva": Fighter("Karine Silva", "Women's Flyweight", 78, 75, 82, 38),
    "Casey O'Neill": Fighter("Casey O'Neill", "Women's Flyweight", 77, 75, 80, 39),
    "Wang Cong": Fighter("Wang Cong", "Women's Flyweight", 70, 68, 65, 30),
    "JJ Aldrich": Fighter("JJ Aldrich", "Women's Flyweight", 73, 70, 70, 28),
    "Eduarda Moura": Fighter("Eduarda Moura", "Women's Flyweight", 72, 68, 75, 38),
    "Gabriella Fernandes": Fighter("Gabriella Fernandes", "Women's Flyweight", 70, 68, 65, 35),
    "Katlyn Cerminara": Fighter("Katlyn Cerminara", "Women's Flyweight", 75, 70, 72, 33),
    "Luana Carolina": Fighter("Luana Carolina", "Women's Flyweight", 70, 68, 65, 30),
    "Tereza Bleda": Fighter("Tereza Bleda", "Women's Flyweight", 68, 65, 70, 28),
    "Carli Judice": Fighter("Carli Judice", "Women's Flyweight", 67, 65, 68, 27),
    "Ernesta Kareckaite": Fighter("Ernesta Kareckaite", "Women's Flyweight", 69, 66, 65, 26),
    "Dione Barbosa": Fighter("Dione Barbosa", "Women's Flyweight", 69, 67, 70, 25),
    "Luana Santos": Fighter("Luana Santos", "Women's Flyweight", 70, 68, 68, 28),
    "Amanda Ribas": Fighter("Amanda Ribas", "Women's Flyweight", 78, 75, 80, 18),
    "Jamey-Lyn Horth": Fighter("Jamey-Lyn Horth", "Women's Flyweight", 70, 68, 72, 15),
    "Veronica Hardy": Fighter("Veronica Hardy", "Women's Flyweight", 70, 65, 75, 15),
    "Julija Stoliarenko": Fighter("Julija Stoliarenko", "Women's Flyweight", 68, 65, 70, 28),
    "Nicolle Caliari": Fighter("Nicolle Caliari", "Women's Flyweight", 69, 67, 68, 29),
    "Bruna Brasil": Fighter("Bruna Brasil", "Women's Flyweight", 72, 70, 65, 23),
    "Fatima Kline": Fighter("Fatima Kline", "Women's Flyweight", 65, 65, 70, 25),
    "Yuneisy Duben": Fighter("Yuneisy Duben", "Women's Flyweight", 66, 64, 68, 24),
    "Melissa Gatto": Fighter("Melissa Gatto", "Women's Flyweight", 74, 70, 75, 18),
    "Brogan Walker": Fighter("Brogan Walker", "Women's Flyweight", 68, 62, 65, 22),
    "Juliana Miller": Fighter("Juliana Miller", "Women's Flyweight", 65, 60, 70, 18),
    "Maryna Moroz": Fighter("Maryna Moroz", "Women's Flyweight", 70, 68, 72, 17),
    "Vanessa Demopoulos": Fighter("Vanessa Demopoulos", "Women's Flyweight", 70, 68, 75, 10),
    "Ariane da Silva": Fighter("Ariane da Silva", "Women's Flyweight", 72, 70, 68, 13),


    "Zhang Weili": Fighter("Zhang Weili", "Women's Strawweight", 90, 88, 85, 70),
    "Virna Jandiroba": Fighter("Virna Jandiroba", "Women's Strawweight", 78, 75, 90, 59),
    "Tatiana Suarez": Fighter("Tatiana Suarez", "Women's Strawweight", 80, 80, 95, 57),
    "Yan Xiaonan": Fighter("Yan Xiaonan", "Women's Strawweight", 85, 82, 70, 56),
    "Amanda Lemos": Fighter("Amanda Lemos", "Women's Strawweight", 88, 80, 75, 57),
    "Jessica Andrade": Fighter("Jessica Andrade", "Women's Strawweight", 85, 80, 85,58),
    "Mackenzie Dern": Fighter("Mackenzie Dern", "Women's Strawweight", 70, 68, 92, 52),
    "Amanda Ribas": Fighter("Amanda Ribas", "Women's Strawweight", 78, 75, 80, 52),
    "Iasmin Lucindo": Fighter("Iasmin Lucindo", "Women's Strawweight", 75, 78, 70, 55),
    "Gillian Robertson": Fighter("Gillian Robertson", "Women's Strawweight", 70, 68, 85, 53),
    "Tabatha Ricci": Fighter("Tabatha Ricci", "Women's Strawweight", 72, 75, 80, 58),
    "Loopy Godinez": Fighter("Loopy Godinez", "Women's Strawweight", 73, 72, 78, 52),
    "Angela Hill": Fighter("Angela Hill", "Women's Strawweight", 75, 78, 70, 53),
    "Tecia Pennington": Fighter("Tecia Pennington", "Women's Strawweight", 70, 75, 72, 53),
    "Loma Lookboonmee": Fighter("Loma Lookboonmee", "Women's Strawweight", 75, 78, 70, 53),
    "Denise Gomes": Fighter("Denise Gomes", "Women's Strawweight", 70, 72, 68, 45),
    "Ketlen Souza": Fighter("Ketlen Souza", "Women's Strawweight", 72, 70, 70, 42),
    "Shi Ming": Fighter("Shi Ming", "Women's Strawweight", 68, 65, 65, 28),
    "Alexia Thainara": Fighter("Alexia Thainara", "Women's Strawweight", 67, 65, 68, 27),
    "Shauna Bannon": Fighter("Shauna Bannon", "Women's Strawweight", 65, 68, 60, 25),
    "Fatima Kline": Fighter("Fatima Kline", "Women's Strawweight", 65, 65, 70, 25),
    "Piera Rodriguez": Fighter("Piera Rodriguez", "Women's Strawweight", 70, 68, 72, 30),
    "Mizuki": Fighter("Mizuki", "Women's Strawweight", 68, 65, 70, 28),
    "Bruna Brasil": Fighter("Bruna Brasil", "Women's Strawweight", 72, 70, 65, 30),
    "Talita Alencar": Fighter("Talita Alencar", "Women's Strawweight", 67, 65, 75, 25),
    "Ariane Carnelossi": Fighter("Ariane Carnelossi", "Women's Strawweight", 70, 68, 70, 30),
    "Yazmin Jauregui": Fighter("Yazmin Jauregui", "Women's Strawweight", 78, 75, 65, 45),
    "Stephanie Luciano": Fighter("Stephanie Luciano", "Women's Strawweight", 70, 68, 68, 28),
    "Julia Polastri": Fighter("Julia Polastri", "Women's Strawweight", 68, 65, 70, 27),
    "Melissa Martinez": Fighter("Melissa Martinez", "Women's Strawweight", 72, 70, 68, 32),
    "Cheyanne Vlismas": Fighter("Cheyanne Vlismas", "Women's Strawweight", 70, 68, 70, 30),
    "Feng Xiaocan": Fighter("Feng Xiaocan", "Women's Strawweight", 65, 62, 65, 20),
    "Puja Tomar": Fighter("Puja Tomar", "Women's Strawweight", 60, 60, 60, 15),
    "Elise Reed": Fighter("Elise Reed", "Women's Strawweight", 68, 65, 65, 25),
    "Vanessa Demopoulos": Fighter("Vanessa Demopoulos", "Women's Strawweight", 70, 68, 75, 30),
    "Marnic Mann": Fighter("Marnic Mann", "Women's Strawweight", 65, 62, 68, 22),
    "Alice Ardelean": Fighter("Alice Ardelean", "Women's Strawweight", 66, 63, 65, 21),
    "Karolina Kowalkiewicz": Fighter("Karolina Kowalkiewicz", "Women's Strawweight", 70, 72, 65, 50),
    "Luana Pinheiro": Fighter("Luana Pinheiro", "Women's Strawweight", 75, 70, 78, 40),
    "Montserrat Conejo Ruiz": Fighter("Montserrat Conejo Ruiz", "Women's Strawweight", 68, 65, 70, 25),
    "Polyana Viana": Fighter("Polyana Viana", "Women's Strawweight", 70, 68, 75, 30),
    "Rayanne dos Santos": Fighter("Rayanne dos Santos", "Women's Strawweight", 67, 65, 68, 24),

    "Kayla Harrison": Fighter("Kayla Harrison", "Women's Bantamweight", 88, 80, 95, 67),
    "Julianna Pena": Fighter("Julianna Pena", "Women's Bantamweight", 82, 78, 88, 63),
    "Raquel Pennington": Fighter("Raquel Pennington", "Women's Bantamweight", 80, 78, 85, 68),
    "Ketlen Vieira": Fighter("Ketlen Vieira", "Women's Bantamweight", 78, 75, 88, 56),
    "Norma Dumont": Fighter("Norma Dumont", "Women's Bantamweight", 82, 78, 75, 53),
    "Macy Chiasson": Fighter("Macy Chiasson", "Women's Bantamweight", 79, 76, 78, 53),
    "Irene Aldana": Fighter("Irene Aldana", "Women's Bantamweight", 85, 80, 70, 57),
    "Ailin Perez": Fighter("Ailin Perez", "Women's Bantamweight", 77, 75, 78, 50),
    "Mayra Bueno Silva": Fighter("Mayra Bueno Silva", "Women's Bantamweight", 80, 75, 82, 52),
    "Yana Santos": Fighter("Yana Santos", "Women's Bantamweight", 77, 75, 80, 45),
    "Karol Rosa": Fighter("Karol Rosa", "Women's Bantamweight", 78, 80, 75,42),
    "Jacqueline Cavalcanti": Fighter("Jacqueline Cavalcanti", "Women's Bantamweight", 75, 75, 75, 30),
    "Nora Cornolle": Fighter("Nora Cornolle", "Women's Bantamweight", 75, 75, 75, 30),
    "Miesha Tate": Fighter("Miesha Tate", "Women's Bantamweight", 76, 72, 85, 40),
    "Joselyne Edwards": Fighter("Joselyne Edwards", "Women's Bantamweight", 75, 76, 70, 45),
    "Chelsea Chandler": Fighter("Chelsea Chandler", "Women's Bantamweight", 76, 74, 75, 40),
    "Daria Zhelezniakova": Fighter("Daria Zhelezniakova", "Women's Bantamweight", 74, 72, 76, 45),
    "Montserrat Rendon": Fighter("Montserrat Rendon", "Women's Bantamweight", 73, 70, 75, 42),
    "Ravena Oliveira": Fighter("Ravena Oliveira", "Women's Bantamweight", 72, 70, 74, 38),
    "Melissa Mullins": Fighter("Melissa Mullins", "Women's Bantamweight", 75, 73, 70, 40),
    "Priscila Cachoeira": Fighter("Priscila Cachoeira", "Women's Bantamweight", 78, 70, 65, 50),
    "Tainara Lisboa": Fighter("Tainara Lisboa", "Women's Bantamweight", 74, 75, 72, 40),
    "Irina Alekseeva": Fighter("Irina Alekseeva", "Women's Bantamweight", 76, 70, 78, 48),
    "Klaudia Sygula": Fighter("Klaudia Sygula", "Women's Bantamweight", 72, 70, 72, 35),
    "Hailey Cowan": Fighter("Hailey Cowan", "Women's Bantamweight", 73, 72, 70, 38),
    "Josiane Nunes": Fighter("Josiane Nunes", "Women's Bantamweight", 79, 78, 70, 55)

}

